version: "3.1"
services:
  pproxy_server:
    build: ./
    restart: always
    container_name: pproxy_server
    ports:
      - 0.0.0.0:8888:8888
    command: python3 -u /usr/local/bin/pproxy -l http://:8888/