version: "3"
services:
  app:
    image: mattermost/focalboard:latest
    volumes:
      - ./data:/opt/focalboard/data
    ports:
      - $PORT:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000