version: '3'

networks:
  default:
    name: proxy_net

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.7
    restart: always
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  avahi:
    image: hardillb/traefik-avahi-helper
    restart: always
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    ports:
      - "5353:5353"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket